export const PASTORS_TEAM = [
  {
    id: 1,
    name: 'Андрей Давыдов',
    rank: 'Старший пастор церкви',
    description: 'Пастор Андрей покаялся в 1993 году в Троицке и сразу нашёл себя в служении. В 1995 году поехал учиться на Библейские семинары в Москву, где и встретил свою будущую жену Карину. В 1997 году женился и уехал вместе с Кариной на миссию в Среднюю Азию, откуда они вернулись только в 2018 году. За 21 год служения они открыли несколько церквей на ближнем востоке. Пока они были на миссии, в семье появилось трое детей, пастор Андрей успел посетить более 40 стран, и заняться всемирным проектом «Сумка Самаритянина» Франклина Грэма. Вот уже три года Андрей Давыдов является старшим пастором церкви «Новая жизнь» Челябинск.',
    thumbnail: '/img/pastors/pastorAndrey.jpg',
  },
  {
    id: 2,
    name: 'Евгений Луканин',
    rank: 'Пастор церкви',
    description: '',
    thumbnail: '/img/pastors/pastorEugene.jpg',
  },
  {
    id: 3,
    name: 'Дмитрий Верин',
    rank: 'Пастор церкви',
    description: '',
    thumbnail: '/img/pastors/pastorDmitriy.jpg',
  },
  {
    id: 4,
    name: 'Анна Давыдова',
    rank: 'Пастор церкви',
    description: '',
    thumbnail: '/img/pastors/pastorAnna.jpg',
  },
  {
    id: 5,
    name: 'Александр Окунев',
    rank: 'Молодежный пастор',
    description: '',
    thumbnail: '/img/pastors/pastorAlexandr.png',
  },
  {
    id: 6,
    name: 'Антон Чернявский',
    rank: 'Подростковый пастор',
    description: '',
    thumbnail: '/img/pastors/pastorAnton.jpg',
  },
  {
    id: 7,
    name: 'Ольга Просвирина',
    rank: 'Детский пастор',
    description: '',
    thumbnail: '/img/pastors/pastorOlga.jpg',
  },
]